language: python
services:
  - docker

secure: "FGEuOwSI1GSoyMVpgZ0E/35hQ5lPPgpRs7m2uxu2enuffmI7+LkFwgTmQqjTo7Xqfh+St1DyEFfHMdchWQ9+b2fypUzQxbmokktcgt1hN/iRA7zj5AyZF5qNykzAzJd03JTWLMILy4cGDwAkxYSiw8myqrmxSXQoJFu02dbi2AeRixwpXgJOl6gzWYFfk794gd0zNvOL/+odUkPUb1MmxhwqfA82MAKdbqaXzi/Ta96pPkXACZiyK2pS3YKvFllTYtJx925gjce8fKMkKBRJnsmaVtf0evU8kXDYSdaUwe82uUf8INf1tjKgTImJPsIA0zgewOPKeKvz6g9r65bTeeHC91qgbd4kq+1UnZboUZ5lSG7mvhqetodga1+xOgqqRHEujyTuXXQNMMSXfFN9EzV854tBgHKLOa4iNFjkoEv3Q0P9Mvxe3jTC+JcCY9zjshf34wY7QKgyDdO6fEaZn2fvrR/8Q5aLHpP6aNc0OvYzIhJbzyyRvoZWo8JRwqnp0iPPFasvGUamfo9t+hj8BnwKYO9yuAKJIqweYvnfzmo0Lju672+ocvsG4deRHdjFhqLeXnKUnoaeivetWMDvmPZUsgw6N7yV0Wp6ajHja6NybQ98sHp75eGjrDtIh9ujxKCqwOOA9WhC33WAIo0HLoj5Py+PMi/aF9TYtO5TtTo="

install:
  - make deps
  
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push