env:
  global:
    - secret: "YEpRwP52ArbAqhRepcLvjhqfAnb58GmLAveVngJRZ/VBzNJDuN3L4IK0EbDR81o/Ne6h3IOr7+fA0mi/ECCcbkNYvsCgbnrfUIA8mHyHApXxqNSylAZ5H2hd5xkdE9bvu4jv8zEprf/ZmgixpUg/3VzKb99HKUdbZr8zc79lSgVJl5HdE8CyZVJhpwDjBYG5Xgppz5QuPkt+NasFP5Cx7ouPlwoF5XhgLt+16TQpddnz1DMyR6NMnU6wjtMf5ngDS78Egk2m8GCjgoIKU2AK160h3jvcJyGwH3Er0v+A7yfUlxoHnQCPyEJs3ZDemkvVctaMcX7qlUDqdiEkCt60hUYX+8Z7Bh+dateYsKdEF/DDQjNd6xf3p5CDiukWtYVQxZIEuX6ww1ZFu6sLoFN1wkHWsCM+yMKIwK/UxcUoEo42K5BuCDQcUz7j9kPSqzFq4NU9MoxmrDSOKunaeJ2mp+fdttDFoEclTbS7UCCBFkawsRZqcivBFoF6rDHarPAacgZP1jPBeMRvVAp1SCUHLAKXORJmoHJqrARbD5KlM2v3FNv1EvWwibQaD5Lxe/cGxlI4NEsYcTl5rsnAgekJfxBBBTXqTt44GeIQ9cTo+auk82uxNl7p3kF+rvZ7++p40SjEqVKR6hiRVCjFRlK8Xjcq5vDFKnR8aRtZuHzPgQo="
language: python
services:
- docker
install:
- make deps
script:
- make lint
- make test
- make docker_build
- make docker_push
