language: python
services:
  - docker
install:
  - make deps
script:
  - make lint
  - make test_xunit
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: stark-dawn-73637
  api_key: ${HEROKU_API_KEY}
